CREATE TABLE veiculo ( 
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT , 
	nome VARCHAR(255) NOT NULL , 
	placa VARCHAR(10) NOT NULL , 
	renavam VARCHAR(20) NOT NULL , 
	marca VARCHAR(255) NULL , 
	modelo VARCHAR(255) NULL , 
	quilometragem DECIMAL NOT NULL DEFAULT '0' , 
	disponivel BOOLEAN NOT NULL DEFAULT TRUE 
) ENGINE = InnoDB CHARSET=utf8;
